[package]
name = "bytemolar-program"
version = "0.1.0"
edition = "2021"
description = "ByteMolar Solana Program"
authors = ["ByteMolar-Dev"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.17.0"
borsh = "0.10.3"
borsh-derive = "0.10.3"
thiserror = "1.0.40"
num-derive = "0.4"
num-traits = "0.2"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test = "1.17.0"
solana-sdk = "1.17.0"

[lib]
crate-type = ["cdylib", "lib"]